### ISSUE TITLE
Revoke pre-Heartbleed SSL certificate

### ISSUE THREAD

**Issue by yyzhuang** [SensibilityTestbed/sensibility-testbed#11]
Due to the Heartbleed bug, we must assume that the old certificate has been leaked. We need to revoke this site's old SSL certificate, and issue a new one.

**Comment by aaaaalbert** [comment]
The current cert expires end of July 2015. That's a good chance to get a new (post-Heartbleed) one.

**Comment by aaaaalbert** [comment]
I just checked and found that sensibilitytestbed.com and sensibilityclearinghouse.poly.edu have fresh certs.
