### ISSUE TITLE
restart Sensibility in the background upon reboot

### ISSUE THREAD

**Issue by yyzhuang** [SensibilityTestbed/sensibility-testbed#14]
Currently when the phone gets rebooted, the Sensibility app will be brought to the foreground and start. We need to start the app in the background instead.

This is a leftover issue of #13.

**Comment by aaaaalbert** [comment]
Fixed in https://github.com/SensibilityTestbed/sensibility-testbed/commit/35a839fb36941cf32f8cd63ab0fbeb3bea72b5f7 .
