### ISSUE TITLE
merge-sl4a: provider location calls do not work

### ISSUE THREAD

**Issue by yyzhuang** [SensibilityTestbed/sensibility-testbed#20]
In merge-sl4a branch, location calls locationProviders() and locationProviderEnabled() do not work, though both calls are implemented similarly as other calls https://github.com/SensibilityTestbed/sensibility-testbed/blob/merge-sl4a/SensibilityTestbed/src/com/googlecode/android_scripting/facade/LocationFacade.java#L133-L148

**Comment by aaaaalbert** [comment]
Superseded by the JNI project. Closing.
