### ISSUE TITLE
The app GUI needs to display consent form

### ISSUE THREAD

**Issue by yyzhuang** [SensibilityTestbed/sensibility-testbed#22]
The consent form should allow the user to agree or disagree. Only when agreed, can s/he continue to install. They can also provide an email address to get a copy of the consent form (optionally).

**Comment by yyzhuang** [comment]
The consent form should look more or less like this https://docs.google.com/document/d/1tb7mORk4NhqLW4KCGmjFd28EIM289ZI_2JRXWwKp8zk/edit?usp=sharing

**Comment by aaaaalbert** [comment]
Implemented in https://github.com/SensibilityTestbed/sensibility-testbed/commit/23b4676e7fe18eabab1ba35f05d2bba3d575239d .
