### ISSUE TITLE
App doesn't run on Android Lollipop

### ISSUE THREAD

**Issue by aaaaalbert** [SensibilityTestbed/sensibility-testbed#27]
Android 5 ("Lollipop") changed a few ways things used to work on previous versions.

This post documents two issues, as tested on a Google Nexus 6 running 5.0: One is that the Python binary is not executable at its default install location; the other is that the executable needs to be rebuilt with PIE (position independent executable) support.
- I installed SL4A_r6 and Sensibility Testbed app via adb.
- The native part of the app launches, proceeds to download the Sensibility tarball, and unzips it
- When native code tries to launch the Python interpreter for the runtime / nodemanager installation, it fails with a nondescriptive error toast (and logcat message): "Sensibility Testbed could not be installed".

File `/sdcard/Android/data/com.sensibility_testbed/files/sl4a/seattle/seattle_repy/installerDebug_0.log` contains all the info about the failed install attempt: (No other install logs are created, as the Python Sensibility installer never runs)

```
09.07.2015 20:43:40 com.sensibility_testbed.InstallerService onStart
INFO: Installer service started
09.07.2015 20:43:40 com.sensibility_testbed.InstallerService$1 run
INFO: Downloading Sensibility Testbed from: https://sensibilityclearinghouse.poly.edu/geni/download/altruistic/seattle_android.zip
09.07.2015 20:43:42 com.sensibility_testbed.InstallerService$1 run
INFO: Download started
09.07.2015 20:43:51 com.sensibility_testbed.InstallerService$1 run
INFO: Download finished
09.07.2015 20:43:52 com.sensibility_testbed.InstallerService$1 run
INFO: Sensibility Testbed extracted successfully
09.07.2015 20:43:52 com.sensibility_testbed.InstallerService$1 run
INFO: Starting installer script
09.07.2015 20:43:52 com.sensibility_testbed.InstallerService$1$1 run
INFO: Installer script finished (not sure if successful)
```

Inspecting the Python binary install dir via `adb` shows

```
shell@shamu:/data/data/com.sensibility_testbed/files/python/bin $ ls -l
-rwxr-xr-x u0_a86   u0_a86      16666 2015-07-09 20:42 python
shell@shamu:/data/data/com.sensibility_testbed/files/python/bin $ ./python
/system/bin/sh: ./python: can't execute: Permission denied
126|shell@shamu:/data/data/com.sensibility_testbed/files/python/bin $ mount | grep /data                                                  
/dev/block/dm-0 /data ext4 rw,seclabel,nosuid,nodev,noatime,nodiratime,discard,nobarrier,noauto_da_alloc,data=ordered 0 0
```

We've seen permission issues before (though this was when we had binaries on an SDcard that was mounted with option `noexec`, i.e. a different situation), so let's try [the old trick](https://android.stackexchange.com/questions/35658/adb-permission-denied-to-run-a-configure-file) again and copy the binary to a (previously) known-executable location. Indeed,

```
shell@shamu:/data/data/com.sensibility_testbed/files/python/bin $ cd /data/local/tmp 
shell@shamu:/data/local/tmp $ cp /data/data/com.sensibility_testbed/files/python/bin/python .
shell@shamu:/data/local/tmp $ ./python
error: only position independent executables (PIE) are supported.
1|shell@shamu:/data/local/tmp $ 
```

So far, it looks like we need to learn building Python for Android from scratch.

**Comment by yyzhuang** [comment]
Lollipop throws an error "only position independent executables (PIE) are supported". Similar errors can be found here http://stackoverflow.com/questions/24818902/running-a-native-library-on-android-l-error-only-position-independent-executab

**Comment by aaaaalbert** [comment]
A bit of progress has been made in https://github.com/aaaaalbert/sensibility-testbed/blob/use-android-studio/SensibilityTestbed/SensibilityTestbed/app/app-release.apk thanks to an updated Python version courtesy of @kuri65536. Thank you very much!

**Comment by lukpueh** [comment]
The app cannot be installed on Android Marshmallow either.
I could reproduce the same issue as above on a Motorola E (2nd generation) running Android v6.0 (Marshmallow).

The mount output looks a little different though:

```
$ mount | grep /data
/dev/block/bootdevice/by-name/userdata /data f2fs rw,seclabel,nosuid,nodev,noatime,nodiratime,background_gc=on,discard,user_xattr,inline_xattr,acl,inline_data,active_logs=6 0 0
/data/media /mnt/runtime/default/emulated esdfs rw,nosuid,nodev,noexec,relatime,upper=0:1015:660:771,derive=multi,noconfine 0 0
/data/media /storage/emulated esdfs rw,nosuid,nodev,noexec,relatime,upper=0:1015:660:771,derive=multi,noconfine 0 0
/data/media /mnt/runtime/read/emulated esdfs rw,nosuid,nodev,noexec,relatime,upper=0:9997:640:750,derive=multi,noconfine 0 0
/data/media /mnt/runtime/write/emulated esdfs rw,nosuid,nodev,noexec,relatime,upper=0:9997:640:770,derive=multi,noconfine 0 
```

However, I can not see how this is connected to the the above mentioned issue.

The good news is, Lollipop Beta Installer does also work on Marshmallow!

**Comment by yyzhuang** [comment]
Lollipop installer is supposed to work on Lollipop though.

**Comment by yyzhuang** [comment]
Sorry, I lied! The Lollipop installer was built because of Google's change in FS permissions. I think all 5.0+ phones have restricted permissions so Lollipop installer will work on them.

**Comment by aaaaalbert** [comment]
Sensibility Testbed app now supports Android 5 ("Lollipop") and upwards. Closing.
