### ISSUE TITLE
Needs a clear installation process

### ISSUE THREAD

**Issue by yyzhuang** [SensibilityTestbed/sensibility-testbed#3]
Origin: https://sensibilitytestbed.com/projects/project/ticket/2

We need to be more clear about installation process. One example is app permissions. 
When a user installs, the app comes up with a message about Python and /or a sl4a installer message. The user clicks yes / accept to both. Then the app had a blank screen. The user is not sure if this was intentional. 

Following this the user clicks to start the process but there's no message indicating if the user has correctly installed it or done anything wrong.

**Comment by aaaaalbert** [comment]
Made irrelevant since we removed SL4A from our APK in SensibilityTestbed@b7202a02def75bb4c20a1325a50f8df9d1e1c7ea
