### ISSUE TITLE
Sensibility Testbed app and Seattle on Android share folders on sdcard

### ISSUE THREAD

**Issue by yyzhuang** [SensibilityTestbed/sensibility-testbed#5]
Origin: https://sensibilitytestbed.com/projects/project/ticket/4

Both Sensibility Testbed app and Seattle on Android install parts of their runtimes in the same folders on sdcard, typically `/sdcard/sla4/seattle`. This also means that Seattle will consider itself installed if it finds Sensibility Testbed's files (and the other way around).

We need to demultiplex folders correctly.

**Comment by aaaaalbert** [comment]
com.sensibility_testbed should use the correct installation method (and thus paths) now. com.seattletestbed needs to be updated too, but the install dirs shouldn't clash anymore.

**Comment by aaaaalbert** [comment]
Tested on a Sony Tablet S running Android 4.0.3 --- both apps install and run side-by-side. (As noted above, this doesn't mean SeattleTestbed is fixed already!)
