### ISSUE TITLE
Sensibility needs a Python JSON parser

### ISSUE THREAD

**Issue by yyzhuang** [SensibilityTestbed/sensibility-testbed#7]
Currently we import lots of built ins in repy.py. We need to code our own or reuse other people's Python JSON parser to process returned sensor data.

**Comment by aaaaalbert** [comment]
The current fix is that Python's `json` lib is `import`ed in `repy.py`, and made accessible through a new, SensibilityTestbed-specific Repy API call.

(I think that in the future, the actual sensor calls will become part of the SensibilityTestbed Repy API.)

**Comment by JustinCappos** [comment]
I would be fine with the sensor calls being implemented in a security layer
instead.  The repy sandbox could just let you open the socket to the
appropriate port, etc.  The layer could actually implement the calls.

**Comment by aaaaalbert** [comment]
@justincappos, a usability side note: Unless implemented via SeattleTestbed/nodemanager#89 / SeattleTestbed/repy_v2#3, using security layers for adding sensors isn't a very user-friendly way to add calls to the API, as witnessed by our GPS blurring experiments:

`start dylink.r2py encasementlib.r2py sensor_layer.r2py blur_wifi.r2py blur_location2city.r2py`
